config/routes.rb
Laposta::Application.routes.draw do
  get "imagenes/new"

  resources :posts do
    resources :imagenes
  end

  resources :imagenes

  resources :miembros

  resources :contactos

  devise_for :admins, :path => "admins", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  resources :slides

  get "home/index"

  root :to => "home#index"

 end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

  validates :nombre, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :length => { :maximum => 100 }, :format => EMAIL_REGEX
  validates :proyecto, :presence => true
end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
  belongs_to :post



  attr_accessible :post_id

  validates :fotografia, :presence => true
  validates_attachment_content_type :fotografia, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :fotografia, :less_than => 4.megabytes

  has_attached_file :fotografia, :styles => {
                                         :thumb => {
                                         :geometry => '190#',
                                         :quality => 80,
                                         :format => 'jpg'
                                        },
                                         :full => {
                                         :geometry => '800x600>',
                                         :quality => 80,
                                         :format => 'jpg'
                                         }
                                      }

  include Rails.application.routes.url_helpers

  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
    {
      "name" => read_attribute(:foto),
      "size" => fotografia.size,
      "url" => fotografia.url,
      "thumbnail_url" => fotografia(:thumb),
      "delete_url" => imagen_path(:id => id),
      "delete_type" => "DELETE"
    }
  end
end

app/models/miembro.rb
class Miembro < ActiveRecord::Base
  validates :avatar, :presence => true
  validates_attachment_content_type :avatar, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :avatar, :less_than => 4.megabytes

  has_attached_file :avatar, :styles => {
                                         :thumb => {
                                         :geometry => '70x70#',
                                         :quality => 80,
                                         :format => 'jpg'
                                       }
                                      }
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :imagenes

  def self.search(search)
    if search
      where('tipo LIKE ?', "%#{search}%")
    else
      scoped
    end
  end


  TIPOS = ['Realización', 'Animación y Post', 'Diseño y Web']

  validates :tipo, :inclusion => { :in => TIPOS }, :presence => true

  validates :foto, :presence => true
  validates_attachment_content_type :foto, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :foto, :less_than => 4.megabytes

  has_attached_file :foto, :styles => {
                                         :thumb => {
                                         :geometry => '190x190#',
                                         :quality => 80,
                                         :format => 'jpg'
                                       },
                                         :preview => {
                                         :geometry => '230x90#',
                                         :quality => 80,
                                         :format => 'jpg'
                                       },
                                         :full => {
                                         :geometry => '800x600>',
                                         :quality => 80,
                                         :format => 'jpg'
                                         }
                                      }





 end

app/models/slide.rb
class Slide < ActiveRecord::Base
  validates :slide, :presence => true
  validates_attachment_content_type :slide, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :slide, :less_than => 4.megabytes

  has_attached_file :slide, :styles => {
                                         :slide => {
                                         :geometry => '950x245#',
                                         :quality => 80,
                                         :format => 'jpg'
                                       }
                                      }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def bodyid
    @bodyid = params[:controller].parameterize
  end

  def bodyclass
    @bodyclass = params[:action].parameterize

    if params[:controller] == 'home'
      @front = 'front'
    else
      @front = 'not-front'
    end

    if current_admin
      @logged = 'logged-in'
    else
      @logged = 'not-logged-in'
    end


    @bodyclass = @bodyclass + ' ' + @front + ' ' + @logged 
  end

  helper_method :bodyid
  helper_method :bodyclass
end

app/controllers/contactos_controller.rb
class ContactosController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:create]

  def create
    @contacto = Contacto.new(params[:contacto])
    ContactMailer.contact_confirmation(@contacto).deliver
    ContactMailer.contact_notification(@contacto).deliver
    create!(:notice => "Mensaje enviado con éxito") { root_path }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contacto = Contacto.new(params[:contacto])
    @miembros = Miembro.all
    @slides = Slide.all
    @posts = Post.order("created_at DESC")
    @ultimos_posts = Post.order("created_at DESC").limit(6)
  end

end

app/controllers/imagenes_controller.rb
class ImagenesController < ApplicationController

  def index
    @imagenes = Imagen.where("post_id = ?", params[:post_id])
    render :json => @imagenes.collect { |p| p.to_jq_upload }.to_json
  end

  def new
    @object_new = Imagen.new    # needed for form_for --> gets the path
  end

  def create
    @imagen = Imagen.new
    @imagen.post_id = params[:post_id]
    @imagen.fotografia = params[:imagen][:path]
    if @imagen.save
      respond_to do |format|
        format.html {                                         #(html response is for browsers using iframe sollution)
          render :json => [@imagen.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@imagen.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def destroy
    @imagen = Imagen.find(params[:id])
    @imagen.destroy
    render :json => true
  end
end

app/controllers/miembros_controller.rb
class MiembrosController < InheritedResources::Base
  before_filter :authenticate_admin!
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticate_admin!
  def index
    @posts = Post.order("created_at DESC").paginate(:per_page => 4, :page => params[:page])
  end
end

app/controllers/slides_controller.rb
class SlidesController < InheritedResources::Base
  before_filter :authenticate_admin!
end

app/helpers/application_helper.rb
module ApplicationHelper

  def paragraph(post, length)
    "#{truncate(post.descripcion, :length => length)}"
  end

  def agregar_clase_segun_tipo(post)
    "#{post.tipo == 'Diseño y Web'? 'foto' : 'video'}"
  end

  def agregar_tipo_como_clase(post)
    post.tipo.gsub(/ /,"").downcase
  end






end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imagenes_helper.rb
module ImagenesHelper
end

app/helpers/miembros_helper.rb
module MiembrosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/contactos/_form.html.haml
- if notice
  = render 'scripts/foobar'
  = render 'scripts/foobar_init'

= form_for(@contacto, :url => { :controller => 'contactos', :action => 'create' }, :validate => true) do |f|
  -if @contacto.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contacto.errors.count, "error")} prohibited this contacto from being saved:"
      %ul
        - @contacto.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre, "Nombre/Empresa"
    = f.text_field :nombre
  .field
    = f.label :email, "E-mail"
    = f.text_field :email
  .field.textarea
    = f.label :proyecto
    = f.text_area :proyecto
  .actions
    = f.submit 'Enviar'

app/views/contactos/edit.html.haml
%h1 Editing contacto

= render 'form'

= link_to 'Show', @contacto
\|
= link_to 'Back', contactos_path

app/views/contactos/index.html.haml
%h1 Listing contactos

%table
  %tr
    %th Nombre
    %th Email
    %th Proyecto
    %th
    %th
    %th

  - @contactos.each do |contacto|
    %tr
      %td= contacto.nombre
      %td= contacto.email
      %td= contacto.proyecto
      %td= link_to 'Ver', contacto
      %td= link_to 'Editar', edit_contacto_path(contacto)
      %td= link_to 'Eliminar', contacto, :confirm => 'Are you sure?', :method => :delete

app/views/contactos/new.html.haml
%h1 New contacto

= render 'form'

= link_to 'Back', contactos_path

app/views/contactos/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @contacto.nombre
%p
  %b Email:
  = @contacto.email
%p
  %b Proyecto:
  = @contacto.proyecto

= link_to 'Edit', edit_contacto_path(@contacto)
\|
= link_to 'Back', contactos_path

app/views/home/_consultas.html.haml
#consultas.region
  #sidebar-form
    %h2.title ¿Cuánto?
    .content
      %p
        Cuéntanos sobre tu proyecto y te enviamos un presupuesto de inmediato.
      = render 'contactos/form'

  #content-map
    %h2.title ¿Dónde?
    .content
      %p.home
        Av. Brasil 1458 - 1460, departamento 604 Torre B, Pueblo Libre, Lima - Perú.
      %p.phone
        (511) 659 8628
      %p.email
        consultas
      .googlemap
        = render 'iframes/googlemap'
      

app/views/home/_laposta.html.haml
#laposta.region
  %section#laposta-description
    %h2.title
      En la Post-A
    .content
      %p
        Audiovisual nos distingue la pasión por <b>CREAR</b>.
        %br
        <b>REALIZAR</b> tus proyectos de manera integral es nuestro mayor compromiso.
        %br
        Te invitamos a <b>VER</b> lo que hacemos...

  %section#posts.column
    =render 'posts/posts'

  %section#staff.column
    =render 'miembros/lista'

  %section#likes.column.last
    %h2.title
      Likes
    .content
      .fb-fake-border
        = render 'iframes/facebook'

app/views/home/_servicios.html.haml
#servicios.region
  %section#servicios-listado
    %ul
      %li.column
        = image_tag '/images/images/servicios/img-servicios-edicion.jpg'
        %h2.title EDICIÓN Y POSTPRODUCCIÓN
        %p Nuestras islas reciben gustosamente sus comerciales, videos corporativos, documentales, videoclips y todo tipo de formato audiovisual. Cortes a la medida del cliente.
        
      %li.column
        = image_tag '/images/images/servicios/img-servicios-animacion.jpg'
        %h2.title ANIMACION Y MODELADO 3D
        %p Creamos estructuras, objetos y personajes en 2 y 3 dimensiones, les agregamos movimiento e imaginación y logramos que nos relaten los mensajes que su proyecto necesita.
        
      %li.column.third
        = image_tag '/images/images/servicios/img-servicios-realizacion.jpg'
        %h2.title REALIZACION DE VIDEO
        %p Concepto, guión, producción y realización. Lo acompañamos en todas las etapas del proceso para crear un producto audiovisual que cumpla con los objetivos de su proyecto.
        
      %li.column
        = image_tag '/images/images/servicios/img-servicios-diseno.jpg'
        %h2.title DISEÑO GRÁFICO
        %p Realizamos diseño publicitario, corporativo y editorial. Nuestra meta es lograr que la imagen de su institución o producto se refleje de la mejor manera en cada pieza, arte o publicación. 
        
      %li.column
        = image_tag '/images/images/servicios/img-servicios-web.jpg'
        %h2.title WEB Y MULTIMEDIA
        %p Las páginas web se han convertido en una poderosa herramienta de comunicación. Lo asesoramos técnica y conceptulamente para crear un website dinámico y de gran impacto.
        
      %li.column.third
        = image_tag '/images/images/servicios/img-servicios-social.jpg'
        %h2.title SOCIAL MEDIA
        %p Las redes sociales generan un contacto directo y continuo con clientes internos o externos. Posicionamos, actualizamos y mantenemos sus redes con una módica inversión y gran rentabilidad.
        

app/views/home/index.html.haml
- page_title! 'Edición y postproducción, animación y modelado 3d, realización de video, diseño gráfico, web y multimedia'

.wrapper
  = render 'layouts/slider'
#scroll-laposta{:style => 'position:relative; top:-30px'}


= render 'laposta'

%h2#servicios-block.page-title [ SERVICIOS ]
= render 'servicios'

%h2#postafolio-block.page-title [ POST-AFOLIO ]
= render 'posts/postafolio'

%h2#consultas-block.page-title [ CONSULTAS ]
= render 'consultas'

app/views/iframes/_facebook.html.erb
<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FPostA.audiovisual&amp;width=246&amp;height=590&amp;colorscheme=light&amp;show_faces=true&amp;border_color&amp;stream=false&amp;header=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:246px; height:590px;" allowTransparency="true"></iframe>

app/views/iframes/_googlemap.html.erb
<div class="map-holder"> 
  <iframe src="http://www.map-generator.org/f302535b-9781-45cb-9a4b-a34ed44d9246/iframe-map.aspx" scrolling="no" height="288px" width="470px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>

app/views/imagenes/new.html.haml
= stylesheet_link_tag 'http://blueimp.github.com/cdn/css/bootstrap.min.css'
= stylesheet_link_tag '/javascripts/jquery-file-upload/css/style.css'
= stylesheet_link_tag "http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css"

%h1= 'Subir imágenes para ' + Post.find_by_id(params[:post_id]).titulo
=render "shared/fileupload"

= link_to 'Volver', post_path(params[:post_id])

app/views/layouts/_footer.html.haml
%footer
  .inner
    = render 'shared/social_links'
    .copyright
      = t('layout.copyright')
    .author
      = t('layout.development')
      = link_to image_tag('/images/kosmyka.png'), 'http://www.kosmyka.com', :id => 'website-author', :target => '_blank'

app/views/layouts/_head.html.haml
= favicon_link_tag 'favicon.png'

= stylesheet_link_tag '/stylesheets/screen.css'
= yield :css

= javascript_include_tag :defaults
= javascript_include_tag '/javascripts/libs/jquery.scrollTo-1.4.2/jquery.scrollTo-min.js', '/javascripts/rails.validations.js'
= yield :scripts

/[if lt IE 9]
  = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

/[if lt IE 9]
  %script{:src => 'http://html5shim.googlecode.com/svn/trunk/html5.js'}
= csrf_meta_tag

app/views/layouts/_menu.html.haml
%ul.menu
  %li#home-top
    = link_to  'Inicio', 'javascript:$.scrollTo("#scroll-top",800);' 
  %li
    = link_to  'LA POST-A', 'javascript:$.scrollTo("#scroll-laposta",800);' 
  %li
    = link_to  'SERVICIOS', 'javascript:$.scrollTo("#servicios-block",800);'
  %li
    = link_to  'POST-AFOLIO', 'javascript:$.scrollTo("#postafolio-block",800);' 
  %li
    = link_to  'CONSULTAS', 'javascript:$.scrollTo("#consultas-block",800);'

  -if current_admin
    %li
      = link_to 'Mensajes de contacto', contactos_path
    %li
      = link_to 'Staff', miembros_path
    %li
      = link_to 'Slides', slides_path
    %li
      = link_to 'Post-afolio', posts_path
    %li
      = link_to 'Desconectarse', destroy_admin_session_path

app/views/layouts/_metas.html.haml
== <meta name="keywords" content="" />
== <meta name="description" content="" />
== <meta name="googlebot" content="index,follow" />
== <meta name="robots" content="index,follow" />
== <meta name="Revisit-After" content="7 days" />
== <meta name="city" content="Lima" />
== <meta name="country" content="Peru" />
== <meta name="state" content="Lima" />
== <meta name="zip code" content="Lima18" />
== <meta name="subject" content="" />
== <meta name="author" content="Kosmyka.com" />
== <meta name="copyright" content="&copy;Todos los derechos reservados." />
== <meta name="geo.placename" content="Lima, Peru" />
== <meta name="geo.region" content="PE-Lima" />
== <meta name="author" content="humans.txt" />

app/views/layouts/_slider.html.haml
= render 'scripts/royal_slider'
= render 'scripts/royal_slider_init'

= render 'slides/lista'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = render 'layouts/metas'
    = render 'layouts/head'


  %body{:id => bodyid, :class => bodyclass }
    - if notice
      %p.notice= notice
    #scroll-top
    #menu-dinamico
      = render 'layouts/menu'
    %header{:role => 'banner'}
      .wrapper
        %h1
          = link_to image_tag('/images/logo.png', :alt => 'La Post-A audiovisual'), root_path
    %nav.main-menu.wrapper
      = render 'layouts/menu'
    %section#content{:role => 'main'}
      = yield


  = render 'layouts/footer'
  = render 'shared/google_analytics'

app/views/miembros/_form.html.haml
= form_for @miembro, :html => { :multipart => true } do |f|
  -if @miembro.errors.any?
    #error_explanation
      %h2= "#{pluralize(@miembro.errors.count, "error")} prohibited this miembro from being saved:"
      %ul
        - @miembro.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :cargo
    = f.text_field :cargo
  .field
    = f.label :correo
    = f.text_field :correo
  .field
    = f.label :telefono, "Teléfono"
    = f.text_field :telefono
  .field
    = f.label :avatar
    = f.file_field :avatar
  .actions
    = f.submit 'Guardar'

app/views/miembros/_lista.html.haml
%h2.title
  Staff
%ul
  - @miembros.each do |miembro|
    %li
      = image_tag miembro.avatar(:thumb)
      .datos
        %h3.nombre
          = miembro.nombre
        %h4.cargo
          = miembro.cargo
        %span.email 
          = miembro.correo
        %span.phone
          = miembro.telefono
      -if current_admin
        = link_to 'Ver', miembro
        = link_to 'Editar', edit_miembro_path(miembro)
        = link_to 'Eliminar', miembro, :confirm => 'Are you sure?', :method => :delete

app/views/miembros/edit.html.haml
%h1 Editing miembro

= render 'form'

= link_to 'Show', @miembro
\|
= link_to 'Back', miembros_path

app/views/miembros/index.html.haml
%h1 Listing miembros

=render 'lista'
%br

= link_to 'Nuevo Miembro', new_miembro_path

app/views/miembros/new.html.haml
%h1 New miembro

= render 'form'

= link_to 'Back', miembros_path

app/views/miembros/show.html.haml
%p#notice= notice

%p
  %b Avatar:
  = image_tag @miembro.avatar(:thumb)

%p
  %b Nombre:
  = @miembro.nombre
%p
  %b Cargo:
  = @miembro.cargo
%p
  %b Correo:
  = @miembro.correo
%p
  %b Telefono:
  = @miembro.telefono

= link_to 'Edit', edit_miembro_path(@miembro)
\|
= link_to 'Back', miembros_path

app/views/posts/_form.html.haml
= form_for @post, :html => { :multipart => true } do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :titulo, "Título"
    = f.text_field :titulo
  .field
    = f.label :tipo
    = f.select(:tipo, options_for_select( ['Realización', 'Animación y Post', 'Diseño y Web'], 'Realización' ) )
  .field
    = f.label :descripcion, "Descripción"
    = f.text_area :descripcion
  .field
    = f.label :url_web, "Url Web"
    = f.text_field :url_web
  .field
    = f.label :video
    = f.text_field :video
  .field
    = f.label :foto
    = f.file_field :foto
  .actions
    = f.submit 'Guardar'

app/views/posts/_postafolio.html.haml
- content_for :scripts do
  = render 'scripts/flare'
  = render 'scripts/flare-init'
  = render 'scripts/isotope'
  = # render 'scripts/isotope_init'

#postafolio.region
  %nav#portafolio-botones{:style => 'display:none'}
    %ul
      %li
        = link_to 'Realización', url_for( :search => 'Realización' )
      %li
        = link_to 'Animación y Post', url_for( :search => 'Animación y Post' )
      %li
        = link_to 'Diseño y Web', url_for( :search => 'Diseño y Web' )

  %nav#portafolio-botones
    %ul{:"data-option-key" => 'filter'}
      %li
        = link_to 'Galería', '#filter', :class => 'active', :"data-filter" => '*'
      %li
        = link_to 'Realización', '#filter', :"data-filter" => '.realización'
      %li
        = link_to 'Animación y Post', '#filter', :"data-filter" => '.animaciónypost'
      %li
        = link_to 'Diseño y Web', '#filter', :"data-filter" => '.diseñoyweb'

  %ul#portafolio-listado
    - @posts.each do |post|
      %li{:class => agregar_clase_segun_tipo(post) + ' ' + agregar_tipo_como_clase(post) }
        = image_tag post.foto(:thumb)
        .content
          %h3.title= post.titulo
          %p
            = paragraph(post, 80) 
          - if post.tipo == 'Diseño y Web'
            .website
              = link_to post.url_web, post.url_web, :target => '_blank'
            = link_to '', post.foto(:full), :class => 'lightbox fotaso',
              :"data-target" => 'flare',
              :"data-flare-gallery" => post.id,
              :"data-flare-thumb" => post.foto(:thumb)
          - else
            = link_to '', '', :class => 'lightbox videaso',
              :"data-target" => 'flare',
              :"data-flare-video" => post.video

          -if current_admin
            .crud
              = link_to 'Ver', post
              = link_to 'Editar', edit_post_path(post)
              = link_to 'Eliminar', post, :confirm => 'Are you sure?', :method => :delete

        - if post.tipo == 'Diseño y Web'
          - post.imagenes.each do |imagen|
            = link_to '', imagen.fotografia(:full), :class => 'lightbox',
              :"data-target" => 'flare',
              :"data-flare-gallery" => post.id,
              :"data-flare-thumb" => imagen.fotografia(:thumb)

app/views/posts/_posts.html.haml
%h2.title
  Posts

.posts-slider
  - @ultimos_posts.each_slice(3) do |slice|
    .content.rsContent
      .rotador
        - slice.each do |post|
          %article
            %div{:class => 'inner rsABlock', :"data-move-effect" => cycle('right', 'left', 'right') }
              %h3
                = post.titulo
              %span.date
                = l post.created_at, :format => :simple
              %p
                = paragraph(post, 60) 
              = image_tag post.foto(:preview), :class => 'rsImg'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1.page-title Postafolio


= link_to 'Nuevo Post', new_post_path

=render 'postafolio'

%br

app/views/posts/index.js.erb
$("#postafolio").html("<%= escape_javascript(render("posts")) %>");

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Foto:
  = image_tag @post.foto(:preview)

%p
  %b Foto:
  = image_tag @post.foto(:thumb)

%p
  %b Titulo:
  = @post.titulo
%p
  %b Tipo:
  = @post.tipo
%p
  %b Descripcion:
  = @post.descripcion
%p
  %b Url web:
  = @post.url_web
%p
  %b Video:
  = @post.video

%p
  %b Imágenes:
  = link_to 'Imágenes', new_post_imagen_path(@post)

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/scripts/_flare-init.html.haml
:javascript
  jQuery(function($){
    $('a[data-target="flare"]').peFlareLightbox();
  });

app/views/scripts/_flare.html.haml
- content_for :css do
  = stylesheet_link_tag '/javascripts/libs/flare/jquery.pixelentity.flare.min.css'

- content_for :scripts do
  = javascript_include_tag '/javascripts/libs/flare/jquery.pixelentity.flare.min.js'

app/views/scripts/_foobar.html.haml
- content_for :css do
  = stylesheet_link_tag '/javascripts/libs/jquery.foobar-2.1/jquery.foobar.2.1.css'

- content_for :scripts do
  = javascript_include_tag '/javascripts/libs/jquery.foobar-2.1/jquery.foobar.2.1.min.js'

app/views/scripts/_foobar_init.html.haml
:css
  .custom-bg .foobar-container {
    /*background:orange;*/
  }
  .notice {display: none}

:javascript
  var mensaje = "#{notice}"


  $foobar({
    "height" : {
      "bar" : 100, "button" : 30
    },
    
    "width": {
      "left": "0", "center": "*",
      "right": "0", "button": "80px"
    },
   
    "display" : {
      //"backgroundColor" : "transparent",
      "border": "solid 3px #000",
      "button": {
        "backgroundColor": "#800",
        "type": "close"
      },
      "theme": {
        "bar": "x-white custom-bg"
      }
    },
    
    "messages": [
      mensaje,
      'Te responderemos en breve'
    ],
    
    "message": {
      "font": {
        "color": "#ff0",
        "size": "24px",
        "shadow": "1px 1px 0 #444",
        "weight": "bold"
      }
    }
  });

app/views/slides/_lista.html.haml
#preface-top
  .royalSlider.rsDefault
    - @slides.each do |slide|
      .rsContent
        = image_tag slide.slide(:slide), :class => 'rsImg'
        = #link_to 'Ver más', slide, :class => 'button rsABlock'
        -if current_admin
          %td= link_to 'Ver', slide
          %td= link_to 'Editar', edit_slide_path(slide)
          %td= link_to 'Eliminar', slide, :confirm => 'Are you sure?', :method => :delete

app/views/slides/edit.html.haml
%h1 Editing slide

= render 'form'

= link_to 'Show', @slide
\|
= link_to 'Back', slides_path

app/views/slides/index.html.haml
%h1 Listing slides

=render 'lista'

%br

= link_to 'Nuevo Slide', new_slide_path

app/views/slides/new.html.haml
%h1 New slide

= render 'form'

= link_to 'Back', slides_path

app/views/slides/show.html.haml
%p#notice= notice

= image_tag @slide.slide(:slide)


= link_to 'Edit', edit_slide_path(@slide)
\|
= link_to 'Back', slides_path